### ISSUE TITLE
Agree on Tech Stack and eslint

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#10]
The current plan so far:

Front-end: React, HTML, CSS, Styled Components
Back-end: Node, Express
Testing: Jest, React Testing Library Supertest

Need to agree the best database language we want to use (e.g. mongo, SQL)

**Comment by thejoefriel** [comment]
@dupreesi @RamyAlshurafa - have been researching a calendar component package we could bootstrap in and I think react-dates would be the best one: http://airbnb.io/react-dates/?selectedKind=DRP%20-%20Day%20Props&selectedStory=with%20some%20blocked%20dates&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

The particular link I've included above shows how it can give us the option to block out dates. So that way we only show the dates when that host has listed their property as available 

It also offers a lot of customization - and it's from airbnb so seems to be a package that is being actively used and worked on

Github link here: https://github.com/airbnb/react-dates

**Comment by RamyAlshurafa** [comment]
@dupreesi @thejoefriel 
are we going to upload images on `firebase` storage like Earwig? or there is another way?

**Comment by thejoefriel** [comment]
@RamyAlshurafa I think let's work on that basis for now yeah. It seems to be the quickest way and we can always modify later

**Comment by dupreesi** [comment]
it all sounds good to me

**Comment by RamyAlshurafa** [comment]
@thejoefriel 
Are you sure that we can use this as a calendar, not a date picker? cause the calendar we have need to open always

**Comment by thejoefriel** [comment]
@RamyAlshurafa I believe we are able to customise it quite a bit so we can default it to being open. For example we could use this version: http://airbnb.io/react-dates/?selectedKind=DRP%20-%20Calendar%20Props&selectedStory=vertical%20with%20full%20screen%20portal&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

And we're able to disable inputs if we ever want to stop people being able to input on it

What do you think? Generally whenever the calendar shows on the website it's because the user is able to input dates etc, so it always needs to be a datepicker as well as showing availability
