### ISSUE TITLE
HOST&INTERN: add edit profile functionality (backend)

### ISSUE THREAD

**Issue by FarahZaqout** [yalla-coop/presspad#102]
**Should wait for #110 to be finished.**

- [ ] Add edit route `/api/users/:id/profile` method `PATCH`.
- [ ] verify that the logged-in user is the profile owner.
- [ ] create a folder `updateProfile`, and check the role `[intern, host/superhost]` and redirect it to the correct controller function (`hostCompleteProfile`, `internsCompleteProfile`).
- [ ] update the existing hostCompleteProfile and internsCompleteProfile controller:
  - [ ] send the data to the query as it is from the front-end (if some data doesn't exist we don't need to update it on the database).
  - [ ] in hostCompleteProfile add update listing collection.
  - [ ] remove the old file uploading middlewares

  ```js
    // update host profile and create new offer
    router.post(
      HOST_COMPLETE_PROFILE,
      softAuthCheck,
      multer(hostCompleteProfile),
      googleStorage(),
      deleteFromServer(),
      hostsCompleteProfile,
    );
  ```

**Comment by FarahZaqout** [comment]
relates #20

**Comment by FarahZaqout** [comment]
req.body should follow #101

**Comment by ashatat** [comment]
**INTERN**
API endpoint: `/api/users/:id/profile`
method: `PATCH`
payload:
```js
  {
    profile: {
      bio,
      favouriteArticle: { title, author, link },
      jobTitle,
      pressPass: { fileName, isPrivate },
      profileImage: { fileName, isPrivate },
      verification: {
        photoID,
        offerLetter,
        reference1: { name, contact },
        reference2: { name, contact }
      }
    }
  }
```

**Comment by FarahZaqout** [comment]
@MohammedYehia Is there work left in this issue?

**Comment by MohammedYehia** [comment]
@FarahZaqout Yes there are some details left for the Host side 
I am working on it and I will close it after making sure everything is complete
