### ISSUE TITLE
Stripe Payment

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#122]
Hi @OliviaPressPad @DarshanSB 

As discussed we're going to use Stripe to carry out the payments. Just to confirm Stripe charges 1.4% + 20p on every transaction. Let me know if this is a major issue. 

Also, regarding this, would this fee come out of PressPad's side, or would you want to pass the fee onto the user?

**Comment by DarshanSB** [comment]
Hi Joe

Yep that’s fairly standard processing fee and the best rate out there for the ease of use. 

I’ll let Olivia answer on which side that charge should come out of.
