### ISSUE TITLE
INTERN: If I selected to pay in three payments, a week before the end of my tenancy I receive an email with a link to carry out the final payment

### ISSUE THREAD

**Issue by ashatat** [yalla-coop/presspad#141]

**Comment by thejoefriel** [comment]
To confirm, this will be a card payment using Stripe. Please refer to https://github.com/yalla-coop/presspad/issues/158

**Comment by OliviaPressPad** [comment]
I think 2 weeks before end of placement would be better as people are slow/forgetful.
