### ISSUE TITLE
INTERN: On the link to carry out payments, I am prompted to enter my bank details to transfer the relevant payment to the PressPad account

### ISSUE THREAD

**Issue by ashatat** [yalla-coop/presspad#142]

**Comment by thejoefriel** [comment]
To confirm, this will be a card payment using Stripe. Please refer to https://github.com/yalla-coop/presspad/issues/158

**Comment by thejoefriel** [comment]
To confirm, this will be a card payment using Stripe. Please refer to https://github.com/yalla-coop/presspad/issues/158
