### ISSUE TITLE
HOST & INTERN:  I can click to see my booking details. On this page we can tick off a checklist of things that must be completed before the stay

### ISSUE THREAD

**Issue by ashatat** [yalla-coop/presspad#143]
I think there is a separate checklist for both interns and hosts?

**Comment by thejoefriel** [comment]
The updated wireframes for these can be found here: https://www.figma.com/file/uVq70RMQDLn04b4Gd1MorQ/PressPad-15.01.2020?node-id=0%3A1

These also include the confirmed checklists. 

Here are the wireframes for reference below. 

**Booking details viewed by Intern**
![Host listing after booking](https://user-images.githubusercontent.com/19708921/72617577-2b3fbe80-3931-11ea-9437-0b2fc41dce2a.jpg)

**Booking details viewed host
![Intern Profile after booking](https://user-images.githubusercontent.com/19708921/72617598-398dda80-3931-11ea-9dd0-47e4c6913ef1.jpg)
**
