### ISSUE TITLE
ORG: I can select to create a discount code

### ISSUE THREAD

**Issue by ashatat** [yalla-coop/presspad#148]
As an organisation, when I can select to create a discount code
  - Enter time period it is valid for and the % discount level
  - It calculates the total potential cost this will be

@thejoefriel  @RamyAlshurafa 
As I understood:
  - the discount will be a percentage for a specific amount of days.
     as an example, if I create a 50% discount for 10days (10 d * 20£ per day) * 0.50 % = 100£
     but if the `Intern` booked only 5 days then the discount will cover 50% of the five days, so he'll get only 50£ and the code will still have 50£ remains on it.

**Comment by RamyAlshurafa** [comment]
@thejoefriel I think we still need the wireframes when `organisation create code`

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa - I've asked for a new wireframe of the organisation dashboard and for creating the code - will keep things simpler if we've got clean wireframes to work off. 

@ashatat - your summary above is correct. I've also created an issue on what we do with any remaining funds that aren't used on a discount code by the time it expires: https://github.com/yalla-coop/presspad/issues/153
