### ISSUE TITLE
ORG: Once a discount code has expired any remaining funds are made available again

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#153]
At the moment when an Organisation adds a discount code it takes it from their 'available' funds even before it's been spent. So for example:

- The Guardian has £500 in their account
- They create a discount code that has a total potential cost of £200
- They have £300 available in their account

This stops them creating more discount codes than they have funds in their account. 

However if they purchase a discount code with a total potential cost of £200, but the intern only uses up £100 of it by the time it expires, then we need to put that remaining £100 back into their available funds. 

So when a discount code expires, we look at what has been spent, if any is left, and if there is that goes back into their available funds

**Comment by RamyAlshurafa** [comment]
this should wait  #195
