### ISSUE TITLE
Admin: I can view the requested payments list

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/presspad#178]
![Presspad Dashboard - payments](https://user-images.githubusercontent.com/34629478/63556614-2fb4a680-c54e-11e9-8f35-bf9f3eb84cbd.png)

**Comment by FarahZaqout** [comment]
API endpoint: /api/payment-requests
method: `GET`

**Comment by FarahZaqout** [comment]
No withdraw requests exist in the database.
Need to add some without breaking tests before the feature is ready for testing.

**Comment by FarahZaqout** [comment]
Turns out database wasn't built. My bad.

**Comment by FarahZaqout** [comment]
Blocker: Does not make sense to have due date tied to a withdrawal request from the account. Current schema has no way to link a due date from collections like "installment" which have due dates on them as well.

Likely a design error or a miscommunication.
