### ISSUE TITLE
HOST: After signing up I am asked to fill out more information to create my profile

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#19]
- [ ] Heading
- [ ] About me section
- [ ] PressPad offer
- [ ] Save button 
- [ ] On successfully filling in and saving, I receive a pop up telling me my profile is currently being reviewed and I will be notified by email 

_NOTE: Waiting for confirmation on whether any fields are required_

**Comment by thejoefriel** [comment]
**REQUIRED FIELDS**
This is from #61 

HOST: Name, Picture (these won't be shown though), Age, Gender, job role, company or freelance, PressPad offer/preference, One calendar input of availability, Verification details

**Comment by RamyAlshurafa** [comment]
Hey @thejoefriel do the offer images required?
