### ISSUE TITLE
HOST & INTERN: Add an on-update trigger to send notifications once an intern stay is approved.

### ISSUE THREAD

**Issue by FarahZaqout** [yalla-coop/presspad#197]
* Add a trigger to the booking model.
  * [ ] trigger runs on update of the ```status``` field.
  * [ ] notifications are sent to the `intern` informing them of the new status of the booking (confirmed/canceled).
  * [ ] sends an email to both `host` and `intern` notifying them of the booking approval. Same thread.

**Comment by ashatat** [comment]
I don't understand why do you need an on update trigger?
the intern stay won't be approved until the host hit the approve button (hence Ramy PR).
so it does make more sense to me to create a notification and send an email when the host hit that approve/reject button :man_shrugging:

**Comment by FarahZaqout** [comment]
So ramy is going to work on this. Okay.

**Comment by FarahZaqout** [comment]
I'll leave it open in case I didn't understand you correctly. We'll see what to do in the stand-up today.

**Comment by ashatat** [comment]
he is not @FarahZaqout

**Comment by RamyAlshurafa** [comment]
Done!
