### ISSUE TITLE
HOST: update host badge after successfully hosting an intern

### ISSUE THREAD

**Issue by FarahZaqout** [yalla-coop/presspad#198]
* add a cron job to update badge in the host profile to true if a stay is successfully completed for the first time.
  * [ ] run the cronjob every day at 03:00 AM.
  * [ ] query the booking model for:
     * bookings that have their ending date 1 day in the past. (range from 00:00 to 23:59:59).
     * populate/lookup on the profile schema with using the host id.
       * badge field is set to false in the host profile.
   * [ ] update the badge field in the profile model from false to true.
   * [ ] upon successful update, send a mail to the host informing them of their new status (verified).

**Comment by ashatat** [comment]
shouldn't we check if the installments, reviews are completed?

maybe this shouldn't be a cron job, could be when the intern add a review for the first booking for the host?

**Comment by FarahZaqout** [comment]
I'm thinking, that if the stay is finished, the host is verified. Rating should probably be different from verification. We should get the others thoughts.
We'll discuss it after the meeting today.
