### ISSUE TITLE
HOST: I can click My Profile to go to the edit profile page and make changes

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#20]
This would be the same as the complete profile page (#19 ) except:
- Form pre-filled with existing input
- Header is 'Here's your profile' 

NOTE:
- They can edit profile before and after being verified
- They cannot be allowed to make fields empty that were previously filled in (i.e. bio, org, job title, profile picture)

**Comment by RamyAlshurafa** [comment]
Closing this user story as it's done except the header title, 
new issue has been created to edit it #245
