### ISSUE TITLE
Receiving emails

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#230]
I went through the process of signing up as a host, but did not receive an email when admin approved my profile.

I also didn't receive any emails when bookings were confirmed etc. 

Have the automated emails been set up? Let me know the best way of double checking all of these

**Comment by ashatat** [comment]
@thejoefriel  the issue here is because we use gmail account, which block sign in attempts from the nodemailer
I change it now and got app password for presspad, so it should work now

**Comment by thejoefriel** [comment]
This has been fixed on last check
