### ISSUE TITLE
Org should only be able to select 10%, 25%, 50% or 100% options for discount

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#231]
At the moment the organisation can create any % discount (e.g. 87%). However, they should only be able to pick one of 4 options - 10% , 25%, 50% or 100% 

![image](https://user-images.githubusercontent.com/19708921/68119792-8732a380-fefb-11e9-8156-2d9f9759b9ca.png)

**Comment by ashatat** [comment]
So I guess it is better if we do it as a dropdown list
