### ISSUE TITLE
Cookie, T&Cs, Legal disclaimers etc

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#235]
@OliviaPressPad @laurapresspad - have you got your T&Cs etc sorted to be added to the website (e.g. you agree to our T&Cs when signing up etc). 

You'll most likely need to sort this out before any version of the website going live

**Comment by OliviaPressPad** [comment]
Yes. Electra should have sent everything across. She has the wireframes and can put the necessary legal verbiage wherever it’s needed.

**Comment by thejoefriel** [comment]
T&Cs have been sent and I've set up a new issue in backlog for cookie banner #487
