### ISSUE TITLE
Required content:

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/presspad#255]
Hey @OliviaPressPad 
could you please provide us with theses data
- [ ]  Calendly link you would like to add to the hosts' checklist
>Video property check (this will be a calendly link)
- [ ] Area interests options
>Area interest (dropdown single select)
- [ ] degree level options
>Degree level (dropdown)
- [ ] disability options
>Disability (dropdown)

**Comment by thejoefriel** [comment]
- [ ] Dropdown list options for profile
- [ ] Terms and Conditions & Privacy policy url links

**Comment by OliviaPressPad** [comment]
Sorry guys. Working through this ASAP now

Terms and Conditions & Privacy policy url links: https://presspad.co.uk/legal-docs/

**Comment by OliviaPressPad** [comment]
Calendly link for home checks: calendly.com/presspaduk/presspad-home-check

**Comment by RamyAlshurafa** [comment]
resources document updated
