### ISSUE TITLE
Bug: booking Calendar validation 

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/presspad#262]
I was able to select a range of dates that include disabled dates
https://www.loom.com/share/2871a2919e294b2d873e38f1da10f334

**Comment by ashatat** [comment]
@RamyAlshurafa  where did this happened?
It doesn't appear with me

**Comment by dupreesi** [comment]
@ashatat @RamyAlshurafa yes you can select dates as in the video but you cannot book them. I will update the error handling for that.
