### ISSUE TITLE
Bug: pages header style (badge with title) 

### ISSUE THREAD

**Issue by ashatat** [yalla-coop/presspad#271]
the badge showing in a weird place

![image](https://user-images.githubusercontent.com/18149438/72248709-7344a580-3600-11ea-84fd-743cad007b5c.png)

**Comment by dupreesi** [comment]
Relates #310 

misplacement is definitely an issue for some breakpoints - not for all. 

<img width="704" alt="Bildschirmfoto 2020-01-21 um 15 47 02" src="https://user-images.githubusercontent.com/23721486/72814415-4da14700-3c65-11ea-83be-e08a9baacc03.png">
<img width="370" alt="Bildschirmfoto 2020-01-21 um 15 46 55" src="https://user-images.githubusercontent.com/23721486/72814416-4e39dd80-3c65-11ea-82c4-ff2b67e11321.png">
<img width="965" alt="Bildschirmfoto 2020-01-21 um 15 46 44" src="https://user-images.githubusercontent.com/23721486/72814417-4e39dd80-3c65-11ea-9b7b-00c1437d70e5.png">
