### ISSUE TITLE
Update what Intern profile looks like when viewed by admin via dashboard

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#281]
This is the view of the admin when looking at an intern. 

Please note, the core layout is exactly the same as the Intern edit profile #280 except the admin cannot edit any of the fields

![Intern Profile - profile tab seen by admin](https://user-images.githubusercontent.com/19708921/72616621-3f82bc00-392f-11ea-80f5-a1fb2fcaeba8.jpg)

![Intern Profile - Details tab seen by admin](https://user-images.githubusercontent.com/19708921/72616781-896ba200-392f-11ea-8716-2caa8da5b41a.jpg)

**Comment by ashatat** [comment]
- Make the main content as a useable component so we could use it in the intern profile  (/my-profile)
