### ISSUE TITLE
Update Host Edit profile

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#283]
This is what the host sees when they first sign up and if they go to edit their profile 

- [ ] Do error validation on each section, so they can't click to offer if they haven't completed the required fields in profile and so on
- [ ] For the dropdowns, if @OliviaPressPad hasn't yet supplied the fields then put in placeholders for now

Please refer to the PressPad flow to double check what is required for the initial sign up process: https://docs.google.com/document/d/1MwGBiMwFDwkuqthvJCmJ301JQKM9aG5wDLTYtoSv7V4/edit?usp=sharing

**Figma link to wireframes for CSS reference here: https://www.figma.com/file/uVq70RMQDLn04b4Gd1MorQ/PressPad-15.01.2020?node-id=0%3A1**

![Host Profile - Profile tab](https://user-images.githubusercontent.com/19708921/72617191-5d045580-3930-11ea-92de-5eec3bd89fd8.jpg)

![Host Profile - Offer tab](https://user-images.githubusercontent.com/19708921/72617199-5f66af80-3930-11ea-875f-e850bba76277.jpg)

![Host Profile - Details tab](https://user-images.githubusercontent.com/19708921/72617203-6261a000-3930-11ea-8cc5-c539e87168b0.jpg)

**Comment by ashatat** [comment]
split the page into sections, each section should be used in viewing Intern profile or updating when used in the Edit profile page.
handle the warning & titles when viewed by the admin
`About you --> Emily Banks` check figma differences
