### ISSUE TITLE
Update host profile viewed by admin

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#285]
This is in the admin dashboard when they select to view hosts to verify / view them

Please note that it looks pretty similar to the edit profile when viewed by hosts, except that the fields cannot be edited. 

Figma link to wireframes for CSS reference here: https://www.figma.com/file/uVq70RMQDLn04b4Gd1MorQ/PressPad-15.01.2020?node-id=0%3A1

![Host Profile - profile tab seen by admin](https://user-images.githubusercontent.com/19708921/72619811-013ccb00-3936-11ea-8316-043a18911856.jpg)
![Host Profile - offer tab seen by admin](https://user-images.githubusercontent.com/19708921/72619648-adca7d00-3935-11ea-99b7-d7632ebfed17.jpg)
![Host Profile - details tab seen by admin](https://user-images.githubusercontent.com/19708921/72619800-fc781700-3935-11ea-8e9b-b1d0f3822f8a.jpg)

**Comment by RamyAlshurafa** [comment]
Duplicated #343
