### ISSUE TITLE
fix undefined / null data handling in ......

### ISSUE THREAD

**Issue by ashatat** [yalla-coop/presspad#354]
- [ ] organisation in booking page title
![image](https://user-images.githubusercontent.com/18149438/73073599-58a3e380-3ec0-11ea-8bc4-c8759f489cd0.png)

**Comment by yosefanajjar** [comment]
In the host profile, there are some undefined values which shouldn't appear this way

![Screenshot from 2020-01-25 13-56-05](https://user-images.githubusercontent.com/44949822/73120741-7897dd80-3f7a-11ea-89ee-d18548e15669.png)

**Comment by Amoodaa** [comment]
@yosefanajjar u fixed it right?
