### ISSUE TITLE
Show host's and intern's reviews on their profiles 

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/presspad#358]
- [ ] Intern's profiles viewed by orgs and hosts
![Intern Profile as seen by host   organisations](https://user-images.githubusercontent.com/34629478/73093203-b3e8cc80-3ee6-11ea-8bca-db98de94bbea.jpg)
---
- [ ] host's profiles viewed by org and intern

![Host listing before booking (2)](https://user-images.githubusercontent.com/34629478/73093815-fe1e7d80-3ee7-11ea-8961-bc24d7816979.jpg)

---
- [ ] booking page viewed by the host
![Booking page for host showing next intern to stay (1)](https://user-images.githubusercontent.com/34629478/73093649-a54ee500-3ee7-11ea-871a-d7d7a07371be.jpg)
---

- [ ] booking page viewed by intern
![Booking page for intern (1)](https://user-images.githubusercontent.com/34629478/73094587-8fdaba80-3ee9-11ea-985d-9610f0d4ec43.jpg)

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa Looks good. Just wondering though why it says the host hasn't hosted any interns but then shows a review? I'm assuming this is to do with the dummy data right? Should we simplify it and just have it say Reviews if there are reviews there to show? And if there are no reviews then "There are currently no reviews"

What do you think?

![image](https://user-images.githubusercontent.com/19708921/73174370-7743ed80-40ff-11ea-9c44-e55a0b8b1dd5.png)
