### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by MohammedYehia** [yalla-coop/presspad#363]
- [x] Copyright © 2019 PressPad -> should be 2020 (using Date function)
- [x] when clicking get start to signup as (ex: an intern) the next page should scroll to the start of the page
- [x] wrong password validation msg (it should ask for uppercase, lowercase, and numbers )
![image](https://user-images.githubusercontent.com/7594617/73110298-8adc3200-3f0e-11ea-884a-83f4f8bc29db.png)
- [x] Area of interest on /intern-complete-profile shows `option A and option B` is this a valid thing??

- [x] weird validation msgs

![image](https://user-images.githubusercontent.com/7594617/73112373-d266bc00-3f16-11ea-8df4-e6b8dbd6c608.png)

- [ ] also the same with the next step and if it is only allowed to enter 50 words then I guess this should be smaller

![image](https://user-images.githubusercontent.com/7594617/73112838-2672a000-3f19-11ea-95c2-cd0d16cb0f23.png)

- [ ] clicking Next Button is not working
 (this was because I filled the input with more than 250 characters)
 
![image](https://user-images.githubusercontent.com/7594617/73112525-57ea6c00-3f17-11ea-9e1e-f0a6b09f7505.png)

- [ ] it is optional but still get is required error

![image](https://user-images.githubusercontent.com/7594617/73112945-c4ff0100-3f19-11ea-983a-34d2b74d2b40.png)

- [ ] I completed all the info and still get this on submit 

![image](https://user-images.githubusercontent.com/7594617/73113070-6423f880-3f1a-11ea-9f5a-cd2985e6ea40.png)

**Comment by Amoodaa** [comment]
Sorry i was working on the stuff u didnt mark as done so its cool, ty, ill continue over it
