### ISSUE TITLE
You should be able to put in a city in host search

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#399]
At the moment you can only put in cities that already exist in the database. Even if it shows no search results, users should be able to enter a city into that field

**Comment by ashatat** [comment]
@thejoefriel 
That meant to be an Autocomplete to help the user search in the available cities "the cities that they have hosts in", but the user can Enter anything he wants, though it is useless to enter a city that won't give you any result :man_shrugging:

**Comment by thejoefriel** [comment]
OK thanks @ashatat - let's leave for now and we can get feedback on this flow when I do user testing on Friday 👍
