### ISSUE TITLE
Birthdate validation 

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/presspad#419]
- [x] date picker shouldn't select dates in futuer
- [x] should disable less than 18 years old interns to make a booking
![image](https://user-images.githubusercontent.com/34629478/73172553-f3443280-410b-11ea-941a-bf8f5e22db37.png)

 @thejoefriel what do you think?

**Comment by thejoefriel** [comment]
I agree they shoudn't do dates in the future. I think we should disable less than 16 years old. And can we have it load at that point (i.e. 16 years ago?)
