### ISSUE TITLE
Error after host accepts a booking request

### ISSUE THREAD

**Issue by yosefanajjar** [yalla-coop/presspad#429]
After the acceptance, the host gets a success message then an error happens

![Screenshot from 2020-01-27 16-04-31](https://user-images.githubusercontent.com/44949822/73181102-496ea100-411f-11ea-9166-1b0f09bc3879.png)

**Comment by ashatat** [comment]
@yosefanajjar  this is just because you haven't filled the `checklistquestions` collection with the questions so when the booking is accepted the  mongoose can't create the checklist

you can use the production build data to fill this collection
