### ISSUE TITLE
Set up zendesk

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#488]
Add Zendesk integration to the platform 

NOTE: This has already been paid for us to integrate by Olivia, but this hasn't been done yet as the platform isn't rolled out so potentially not yet worth paying the ongoing cost. Joe needs to speak to @OliviaPressPad about this to see when would be best to set up, but putting this note here to make sure it's not double charged

**Comment by OliviaPressPad** [comment]
I think September or October would be best @thejoefriel
