### ISSUE TITLE
UX User Testing

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#521]
## Purpose of this issue:
- [ ] Store the UX user testing sessions
- [ ] Link to the Figma prototype
- [ ] Link to User Testing script(s)
- [ ] Link to User Testing Feedback Form (to be filled in by one of our team)
- [ ] Discuss which elements we feel are important and require wireframe changes via comments in this issue

## Roles
Every User Testing session must be attended by min. 2 people  

## Documentation
All scripts and feedback stored here: TBC

## Prototype
TBC

## Agreed User Testing Sessions (please update here)

**WRITE USER TYPE HERE**
- Name:
- Email:
- Time:

**WRITE USER TYPE HERE**
- Name:
- Email:
- Time:

**WRITE USER TYPE HERE**
- Name:
- Email:
- Time:

**WRITE USER TYPE HERE**
- Name:
- Email:
- Time:

**Comment by OliviaPressPad** [comment]
@thejoefriel Do you need me to do anything with this issue?
