### ISSUE TITLE
Automated Emails to Users - Copy

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#522]
Below is a list of the automated emails that users get sent (broken down by user type). 

@OliviaPressPad @laurapresspad let us know if there should be more. And please for each one can you send us the copy that you would like in each one (including any logos/images you want us to include). I'd suggest you add the copy for each one as a comment as that'll keep things nice and simple, then mark it as covered on the list below. 

We would suggest not going to heavy on images, as this makes it more likely to hit spam filters. Plus, generally it's found now that users respond better to emails that look like genuine emails rather than obvious marketing ones. 

### Intern

**Initial sign up with email and password**
- [ ] Welcome email and telling them to finish their profile to be able to make bookings

**Has signed up but hasn't completed profile after 3 weeks**
- [ ] Prompt email to complete profile and why

**Profile approved by PressPad**
- [ ] Email celebrating them finishing profile and being approved and now they can stay with hosts

**Profile rejected by PressPad / changes requested**
- [ ] Email telling them their has been an issue with their profile and specifying what this issue (or issues are)

**Booking request is rejected**
- [ ] Email telling them they have been rejected and why

**Booking request is accepted but payment is required**
- [ ] Email telling them they have been accepted with link to pay to complete booking and that they have 48 hours

**Host cancels booking within this 48 hour period before payment**
- [ ] Email telling them the booking has been cancelled

**Intern completes payment for booking / or no money was required for booking**
- [ ] Emailing telling them the booking is complete and connecting them with the host in the same email 

**1 week prior to an intern staying with host**
- [ ] Emailing telling them their stay is in a week's time and pushing them to any useful resources for being a good guest

**During stay intern hasn't paid the latest payment within 7 days**
- [ ] Email telling them that payment is overdue 

**Intern still doesn't pay within a further 48 hours**
- [ ] Email telling them that the booking is going into termination and someone from PressPad will in touch shortly to resolve this personally

**Host has requested cancellation after payment (i.e. once a booking is confirmed)**
- [ ] Email telling them that a cancellation request has been submitted and that PressPad will be in touch shortly to resolve this personally

****

### Host

**Initial sign up with email and password**
- [ ] Welcome email and telling them to finish their profile to be listed on the website

**Has signed up but hasn't completed profile after 3 weeks**
- [ ] Prompt email to complete profile and why

**Profile approved by PressPad**
- [ ] Email celebrating them finishing profile and being approved and now their listing is live

**Receive a booking request**
- [ ] Email telling them they have a booking request with link to view and respond

**Accepted a booking request but the intern didn't pay within 48hours or cancels in this period**
- [ ] Email telling them the booking has been cancelled and why

**Intern completes payment for booking / or no money was required for booking**
- [ ] Emailing telling them the booking is complete and connecting them with the intern in the same email 

**1 week prior to an intern staying with host**
- [ ] Emailing telling them their stay is in a week's time and pushing them to any useful resources for being a good host

**During stay intern hasn't paid the latest payment within 7 days**
- [ ] Email telling them that payment is overdue 

**Intern still doesn't pay within a further 48 hours**
- [ ] Email telling them that the booking is going into termination and someone from PressPad will in touch shortly to resolve this personally

**Intern has requested cancellation after payment (i.e. once a booking is confirmed)**
- [ ] Email telling them that a cancellation request has been submitted and that PressPad will be in touch shortly to resolve this personally

****
-----

### Organisation

**Intern they have provided a discount code for is 9 days overdue (i.e. 7 days + then extra 48 hours notice they are given) during a stay**
- [ ] Email telling them that the booking is going into termination and someone from PressPad will in touch shortly to resolve this personally

**Comment by OliviaPressPad** [comment]
Here: https://drive.google.com/open?id=18kPMuETy_7ZPzHAut9oNYDlxgmEyQfv_
