### ISSUE TITLE
Required from PressPad for Booking

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#526]
This outlines what we need from PressPad to deliver the **Booking** flow functionality

---

### Acceptance Criteria:
- [x] Confirm urgent@presspad.co.uk is set up as an email address
- [ ] Provide copy for the following emails: (relates to #522 )
    - [ ] **Booking request is rejected** - Email telling them they have been rejected and why
    - [ ] **Booking request is accepted but payment is required** - Email telling them they have been accepted with link to pay to complete booking and that they have 48 hours

**Comment by OliviaPressPad** [comment]
Have asked our freelance copy writer, Rachel, to make sure this is in the list of automated emails she's already written up and can be found here: https://drive.google.com/open?id=18kPMuETy_7ZPzHAut9oNYDlxgmEyQfv_ (Give her 1-2 days to complete it as I don't think she's working today cos it's a bank holiday)
