### ISSUE TITLE
Update menu 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#527]
In the updated wireframes we have moved to left-sided menu when they are logged in. Since we are working on pages that will have this new design for the **Booking** flow we should set this up.

_Note: Wireframes still TBC so this issue may need to be updated following that_

---

### Acceptance Criteria:
- [x] Left-sided menu on desktop for logged in users when using their dashboard
- [x] Following links per user type:
    - [x] Intern: Dashboard / Bookings / Payments / Profile / Settings / Log Out 
    - [x] Host: Dashboard / Bookings / Payments / Profile / Settings / Log Out
    - [x] Org: Dashboard / Profile / Settings / Log Out
    - [x] Admin: Dashboard / Hosts / Interns / Organisations / Payments / Booking Requests / Log Out
- [x] Moves to usual top menu with hamburger for mobile/tablet
- [x] Top menu for all other pages

**Comment by RamyAlshurafa** [comment]
we need to create two different common layouts, and they should be dynamic to accept the body of the page and align it in a proper way with the navbar

**Comment by RamyAlshurafa** [comment]
question: what about the organisation dashboard?

**Comment by thejoefriel** [comment]
> questions:
> 
> * what about the organisation's dashboard?
For the organisation's dashboard we should use the same left-side menu so there's continuity for dashboards across all users. Any work on organisation pages isn't needed for the booking flow this is part but if you feel it makes sense we can update the menu to cover all user types. I've updated the description to do this.
