### ISSUE TITLE
Update Host Profile Page

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#529]
__Is there an associated User Story?__

- If I have selected specific dates(from search page) when I click on to view a host, these dates are automatically selected in the profile
- When viewing a host profile, I can enter a discount code to see the change in price
- The price for the first 14 days of my stay is always £0
- I can see how long the host typically takes to respond to a booking request

---

### Acceptance Criteria:
- [x] Update style to be in line with wireframes
- [ ] Dates in calendar are automatically selected if dates were used to filter hosts in the search page
- [ ] On blur, run query to check if the code exists
- [x] Any stay for 14 days or less is always £0 
- [ ] Calculate the average days the host takes to respond (rounded to the nearest day). Default at 7+ days
- [x] Only show the bursary checkbox if they are not logged in as an intern

**Comment by RamyAlshurafa** [comment]
- need to store the total hours taken to response and the total number of requests, and on each time host response to a request, increment these two fields

**Comment by dupreesi** [comment]
also make sure page is accessible to all users but that the button text prompst to sign up if not loggedIn

**Comment by dupreesi** [comment]
also integrate groupon code check (if enough money and valid code)
