### ISSUE TITLE
Check internship is valid for booking

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#530]
__Is there an associated User Story?__

If my requested start date is earlier than my internship start date (in my profile) by 3 days or more, or later than my internship end date (in my profile) by 3 days or more, I am prompted to update my internship details

---

### Acceptance Criteria:
- [ ] Update profile data for interns, to make sure it includes:
    - [ ] Dates of internship
    - [ ] Contact name for internship
    - [ ] Contact email for internship
    - [ ] Contact number for internship
    - [ ] Organisation name for internship 
    - [ ] Proof of internship
- [ ] Update db request so that the code (if applied) is added to the booking
- [ ] Update sign up / edit profile page to include these intern fields (following wireframe)
- [ ] Check if internship start date in profile is earlier than booking request start date by 3 days or more
- [ ] Check if internship end date in profile is earlier than booking request end date by 3 days or more
- [ ] Modal shown to user if they don't meet the criteria
- [ ] Form for intern to update those specific intern fields in the modal
- [ ] Updating in modal updates their profile data 
- [ ] Run checks on any updated data too

**Comment by RamyAlshurafa** [comment]
- i think we should create another issue for `Update sign up / edit profile page`, and keep this just to check the request period and redirect to "profile" only

**Comment by thejoefriel** [comment]
> * i think we should create another issue for `Update sign up / edit profile page`, and keep this just to check the request period and redirect to "profile" only

Cool, just to confirm though, the user wouldn't have to go to the sign up / edit profile page. They would be able to fill in the internship fields in that modal and this would update their profile
