### ISSUE TITLE
As Admin I review all intern booking requests

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#531]
__Is there an associated User Story?__

- As an intern having completed a booking request, I am shown a success message and that I will receive a response shortly
- As admin I can see the booking request in a Booking Requests tab in the dashboard ordered by closest to stay
- As admin I can click a booking request to expand and quickly view the internship details and a link to download the proof of internship
- As admin I can approve the request and the status is updated to awaiting response
- As admin I can reject the request and I am prompted to enter a message to send to the intern

---

### Acceptance Criteria:
- [x] Add Booking Request tab in Admin dashboard
- [x] Add table for each booking with columns
    - [x] Intern
    - [x] Host
    - [x] Start date of stay
    - [x] Status (Accepted, Rejected, Awaiting Admin, Awaiting Host)
    - [x] Approve / Reject button (if booking is Awaiting Admin)
- [x] Order bookings based on those closest to current date
- [x] Make each row expandable by clicking to show internship details (organisation name, contact name, contact email, contact number, link to download proof of internship)
- [x] Don't show booking request to Host while Awaiting Admin
- [x] If approved, render the booking in Host's Booking Requests
- [x] If rejected, show modal to enter message to send to intern and confirm button

**Comment by RamyAlshurafa** [comment]
- need to add "view booking" link to view full details of the booking and the checklist for the intern and host?

**Comment by thejoefriel** [comment]
> * need to add "view booking" link to view full details of the booking and the checklist for the intern and host?

Good point on view booking. 

We don't need a checklist any more for intern and host, as they are now made to do everything before their profile is approved. However there will be tips on how to be a good host / guest etc. That will be covered in https://github.com/yalla-coop/presspad/issues/534 and https://github.com/yalla-coop/presspad/issues/532 (will make more sense I think once we get the wireframes sorted)
