### ISSUE TITLE
As a host I can review booking requests (update)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#532]
__Is there an associated User Story?__

_Add it here:_
- If I try to accept a request when I have another pending request overlapping the dates, I see a warning message and that the other booking will be automatically rejected. I can confirm or cancel.
- If I reject a request I am prompted to enter a message for the intern to explain why

*Note: once wireframes are finalised, we'll update the acceptance criteria with the key differences on the bookings page based on status*

---

### Acceptance Criteria:
- [ ] Update booking details page to be in line with wireframes
- [ ] Render the correct view for each status of booking page
    - [ ] Accepted
    - [ ] Rejected
    - [ ] Completed 
    - [ ] Pending
- [ ] When host clicks to accept, check if dates overlap with any other requests
- [ ] If overlapping, render warning modal with confirm & cancel buttons
- [ ] When rejecting, show host a text field to enter message and submit button
- [ ] If overlapping and host accepts booking, automatically cancel other overlapping bookings

**Comment by RamyAlshurafa** [comment]
- need to change the UI completely

**Comment by thejoefriel** [comment]
> * need to change the UI completely

Are you able to provide more details on what you mean? Would be good to add this as acceptance criteria.
