### ISSUE TITLE
Required from PressPad for Payment 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#539]
This outlines what we need from PressPad to deliver the **Payment** flow functionality

---

### Acceptance Criteria:
- [ ] Set up accounts@presspad.co.uk (or something similar where all transaction related emails can be sent)
- [ ] Provide details of what they want on the organisation payment receipts

**Comment by OliviaPressPad** [comment]
accounts.payable@presspad.co.uk has been set up. 

Organisation payment receipts should bill us as: Hosting & Mentorship Services
