### ISSUE TITLE
Database updates 

### ISSUE THREAD

**Issue by RamyAlshurafa** [yalla-coop/presspad#541]
reflecting the changes on DB( for the first sprint)
- users
  - add: `accept_automatically ` - boolean
  - add: `respondingTime` - time in ms
  - add: respondedRequests` integer

- merge "profile" table into "user" table (optional-enhancment).
- merge "listing" table into "user" table (optional-enhancment).

to be continued

**Comment by thejoefriel** [comment]
- user  
    - update internship address 
      ``` 
      internshipAddress: {
      addressline1: {
        type: String,
        required: true,
      },
      addressline2: {
        type: String,
        required: false,
      },
      city: {
        type: String,
        required: true,
      },
      postcode: {
        type: String,
        required: true,
      },
    ```

    - internship_start_date - date
    - internship_end_date - date
    - internship_contact_name - string
    - internship_contact_email - string
    - internship_contact_number - number

- booking
    - status - update options to ["awaiting admin", "awaiting host", "awaiting deposit", "confirmed", "completed", "cancelled"]
