### ISSUE TITLE
Confirm PressPad's payment

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#552]
Hi @OliviaPressPad @laurapresspad - can you please confirm what % of each payment goes to PressPad please?

At the moment we currently have it that the host gets 100% of what the intern pays and then they can choose to donate if they wish to PressPad. Is that still in the case? If not, how much of what the intern pays goes to PressPad before the host receives anything?

**Comment by OliviaPressPad** [comment]
Hi Joe - Hosts get half and we get half. So we would get £10 a night and host gets £10 a night so it's exactly 50-50. 10% of our money - so £1 per night goes into the bursary fund. Hope this helps and sorry that wasn't clear before.

**Comment by thejoefriel** [comment]
Thanks @OliviaPressPad 

@ashatat @RamyAlshurafa @dupreesi - looping you in on this when we start working on the payment milestone. 

Also @ashatat you asked about the £20 a day vs £150 a week. @OliviaPressPad has confirmed now that it is just simply £20 a day 👍
