### ISSUE TITLE
What do we have sorted in way of GDPR?

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#57]
Since we're emailing people etc do we have any thoughts yet on GDPR? Just thinking things like double opt-in sign up, T&Cs, cookie disclaimers, being able to delete your account. 

Or at this stage of the process is this not so a high a priority as the main focus is being able to get to the next stage of user testing in a beta mode?

**Comment by OliviaPressPad** [comment]
I think we need to comply with GDPR from the get-go, no? Isn't it better to build it with this in mind than tack it on the end? The lawyers might know more about this. At its most basic we just need to have the policy somewhere in the footer alongside all our other policies no?

**Comment by thejoefriel** [comment]
I believe so! If we can get Darshan's lead on this that'd be great!

**Comment by thejoefriel** [comment]
Closing this issue as we'll tackle it in the upcoming GDPR flow
