### ISSUE TITLE
Create Bookings Page for Host&Intern

### ISSUE THREAD

**Issue by ashatat** [yalla-coop/presspad#600]
__Is there an associated User Story?__

_Add it here:_

---

### Work to be done
- create common component only inside Bookings folder
  - currentBooking component
![image](https://user-images.githubusercontent.com/18149438/83873825-2b542580-a73d-11ea-8df7-4393c4f4f767.png)
  - upcomingBooking component
![image](https://user-images.githubusercontent.com/18149438/83874070-9867bb00-a73d-11ea-9342-5d1a53550131.png)
- create bookings page for both Intern and Host according to Figma

---
### Acceptance Criteria:
- [ ] Make sure Booking Requests and Previous Bookings are expandable drawers, and are initially closed when you arrive on the page
- [ ] All rows in the booking requests and previous bookings should click to that booking
- [ ] Ensure mobile repsonsive

**Comment by thejoefriel** [comment]
Hey @ashatat @dupreesi - I actually after the last sprint spent a bit of extra time creating these common components. I ran out of time so not sure if they're 100% there and will need some tweaking but a lot of the design work is there for you hopefully. I've pushed the branch: https://github.com/yalla-coop/presspad/pull/610

You can see both cards in storybook and I've made them responsive. 👍
