### ISSUE TITLE
Profile - required fields?

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#61]
When the host or intern are filling in their profile (e.g. organisation, job description, presspad offer) are there any required fields before they can hit submit?

**Comment by OliviaPressPad** [comment]
Yes. Darshan should have passed this on as we discussed all this in the Trello at length. 

INTERN: Name, Picture, About me, Age, Gender, PressPad Ask
HOST: Name, Picture (these won't be shown though), Age, Gender, job role, company or freelance, PressPad offer/preference, One calendar input of availability, Verification details

**Comment by thejoefriel** [comment]
Thanks @OliviaPressPad ! Sorry if I've missed this on the Trello board!
