### ISSUE TITLE
When paying an accepted booking request the page crashes / booking status doesn't get updated

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/presspad#623]
When paying for an accepted booking request -> page crashes 
When solving this by updating relevant parts of the InternView/index 
```
let paymentInfo;

    if (firstUnpaidInstallment) {
      paymentInfo = firstUnpaidInstallment;
    }
    if (newInstallments) {
      paymentInfo = newInstallments;
    }
    if (
      installments[0] &&
      installments[0].transaction &&
      !firstUnpaidInstallment
    ) {
      [paymentInfo] = installments;
    }
```
I can now pay but the booking status remains pending.
https://www.loom.com/share/d08bed60a9c640289cf6af5d3897f7d0

**Comment by ashatat** [comment]
@dupreesi  
I couldn't regenerate the bug
let's have a call about it on Monday
