### ISSUE TITLE
How do we calculate the price for staying with a host? 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#63]
Is there a fixed per day rate?

**Comment by OliviaPressPad** [comment]
So the prices are a flat rate of £150 a week at the moment. I guess it would be good to have scope to change that when we expand beyond London where prices should be cheaper but that's how we do it for now. That would mean just over £20 a night which we can use as the cost if they book say a couple of days or 10 days etc. So a 10 day stay would be £150 + 3x£20 = £210. Sound good to you? If there is anything that doesn't just from the perspective of common sense or a user let me and Darshan know (is Darshan onboarded to the Github project yet? We should do that ASAP!).

**Comment by thejoefriel** [comment]
Thanks @OliviaPressPad - makes sense. 

No, not heard back from Darshan on the emails. If you're able to give a prod that'd be great. I can also send a chaser again today :)
