### ISSUE TITLE
BUG: ADMIN trying to look at DBS certificate of host or intern (Google Chrome/Laptop/Mac/OS)

### ISSUE THREAD

**Issue by OliviaPressPad** [yalla-coop/presspad#633]
__Is there an associated User Story?__
ADMIN trying to look at DBS certificate of host or intern 

_Add it here:_
When I click on view certification on an intern or host’s DBS certificate I get this message:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Details>No such object: presspad-2ff87.appspot.com/fake-DBSCheck.pdf</Details>
</Error>

--

### Acceptance Criteria:
- [ ] Add each acceptance criteria as checklist like this...

**Comment by RamyAlshurafa** [comment]
This is  not a bug, its just related to the fake data we use in development, so this wouldn't happen in production
