### ISSUE TITLE
Quick Set Up Summary & Agree User Stories 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#67]
Hi! You'll see we've broken down all the functionality down to user stories. Everything we've suggested as trying to achieve in this first sprint can be found under the milestone **sprint-1**

A couple of user stories have been tagged as **BONUS** (you can find these in the issues but searching for **BONUS**) as we will try to get to them in this sprint if we have time. 

We will also try to get to a mobile version of the website, but this has been labelled as BONUS at this stage also as we'd require mobile wireframes of all the pages to do this properly. 

### Functionality we will leave out in this stage

We have also written our user stories for functionality we feel we'd need more time to implement. You can find all these under the milestone **future-sprint**

You'll see that the majority of user stories are centred on the organisation user and just giving them a simple dashboard. 

In addition we feel the whole currency / credits transaction process would require further time beyond what we've got so far, as this requires building a whole payment system. At this stage we'd recommend that when a request is accepted you will get an email providing all details of the request and letting you know whether they want to receive payment to their account or donate the payment to PressPad. That way you can then go ahead and manually carry out the payment via invoicing through email. 

This will mean we can still build out the whole flow, enabling you to start testing it with users as soon as possible.

Think this covers everything! Please let me know if you disagree with anything we've outlined or if you feel there are any user stories at all that have been missed.

**Comment by OliviaPressPad** [comment]
Hi Joe - it would be really great to have the payment stuff done as well. Can you work out how much longer that will take? The idea is that it's all in the website. If we have to start manually invoicing that's going to cost us time and money we can't afford. The idea is to keep as much of it automated through the website - emails are a blackhole! Let me know! Thanks!

**Comment by thejoefriel** [comment]
Hi @OliviaPressPad - yeah totally know what you mean re emails! Unforutnately we would really need Darshan's advice on this to be honest as building out a whole payment system would take more time than we currently have allocated and we'd need advice on this to make sure it's done properly.
