### ISSUE TITLE
Can users view Hosts even if they aren't signed in?

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/presspad#70]
@OliviaPressPad  Do you want them to always have the option to see what's on the platform but not give them the option to book (instead giving them a link to sign up) or do they need to register before they can view the list of hosts?

**Comment by OliviaPressPad** [comment]
Can we show some entries for the profiles and not all of them? So they can see something v.basic and then they can sign up to see more? Incentivizes sign up. Otherwise if we don't show them something they might not get interested in the first place? Is this easy to do?

**Comment by thejoefriel** [comment]
Sure thing, we can have a Hosts page that shows just three entries (that aren't clickable) and has a link telling them to sign up to view more.

**Comment by thejoefriel** [comment]
I've set up an issue for this #74
