### ISSUE TITLE
Check bursary and coupon code logic

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/presspad#808]
**Setup**
1. pull latest develop branch and npm run build:data:dev
2. Log in as organisation, add funds (>500 £) and create a 50% coupon for period 01.04.2021 - 31.05.2021

**Check DB**
- Approved Bursary application for intern user
startDate: 2020-09-21T15:47:05.394+00:00  endDate: 2021-09-01T15:47:05.394+00:00
Discount rate: 20%
London weighting: true

- check if coupon dates are 3 days before and after selected coupon period 

**A. Test to input coupon code as a logged out user** 
-> dummy Listing should be available starting from April 2021
- [x] Select a period of > 14 days and input a coupon code that is already assigned to an intern: use ‚halfpay‘ -> check error message
- [x] Check the same for a valid coupon: select a period which falls into the coupon period (enter the one you’ve created) -> check if discount works
- [x] Check for a period outside of coupon period (e.g. September 2021) -> check error message

**B. Test bursary (Log in as intern@test.com)**
- [ ] select period that is within bursary period, e.g April-may 2021 -> check reduced price
- [x] Select period that’s outside of bursary (e.g. October 2021) -> check error message and if request button / coupon input are disabled

**C. Test bursary and coupon code (Log in as intern@test.com)**
- [x] Select period where bursary applies and where the discount code you’ve created is also valid (e.g. April/May 2021) -> check if coupon reduction works
- [x] Select valid bursary period which falls outside of coupon period, e.g June 2021 -> check if redirection to update internship details works and that you cannot update your dates due to approved bursary

- [x] additionally: test coupon code that is already used by another intern (log in as other intern and try 'halfpay' for instance

**C. Test coupon without bursary**
- [x] change the status of the approved bursary in db to ‚request‘ to make it invalid and refresh host profile page
- [x]  Select period that falls outside of coupon period, e.g. June 2021 and enter coupon code -> check if redirection to update internship details with ability to update internship dates -> update details accordingly and complete request

**D. Test to pay for reduced booking in instalments** 
- [x] Re-run dummy build, log in as org, add funds > 900£ and create coupon for 01.04.2021 - 30.06.2021
 - [x] Log in as intern, go to host profile and select booking period valid for both bursary and coupon (needs to be more than 8 w (e.g. 10.4 - 29.06.2021, enter coupon code -> check if both reductions worked and request to stay 
- [x] Log in as admin and approve booking request -> log in as intern and find booking request -> check if bursary was applied and if coupon code is active -> check reduction
- [x] check if payment options are correctly (installments or full pay)
- [x] enter coupon code that doesn't match bursary dates (e.g. 'sk1t1qoVm') -> check error message

**Comment by thejoefriel** [comment]
I don't think the bursary discount is getting applied correctly - have set up an issue for this: https://github.com/yalla-coop/presspad/issues/830

**Comment by thejoefriel** [comment]
Completed and have created relevant issues so now closing this
