### ISSUE TITLE
When I add a user photo it looks really small in the complete-profile section.

### ISSUE THREAD

**Issue by dupreesi** [yalla-coop/presspad#81]
Screengrab: http://www.clipular.com/posts/4559850340876288?k=3pFTUzHGQOvvBeFZ5ahP0C2aRPw

**Comment by RamyAlshurafa** [comment]
@dupreesi I used the same dimensions from the figma, do you have a suggestion about how to display it?

**Comment by thejoefriel** [comment]
Hey @RamyAlshurafa Not sure if that screengrab is working so pasted it below

I think it just needs to be a bit bigger - I'd say double the size. There seems to be plenty of room between it and the other elements so should be able to be larger without affecting layout

![image](https://user-images.githubusercontent.com/19708921/59338065-9c632780-8cf9-11e9-8255-2aeffff2aa69.png)

**Comment by RamyAlshurafa** [comment]
cool thanks @thejoefriel 
will fix it in the intern profile PR which has the same feature
